# apps/events/migrations/0001_initial.py
# Generated by Django 5.1.3 on 2025-02-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '__first__'),
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('half', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatchEventTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('icon', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'match_event_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatchSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home_team', models.BooleanField(blank=True, null=True)),
                ('numer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_squad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('match', 'Match'), ('training', 'Training'), ('custom', 'Custom')], max_length=1024)),
                ('descritpion', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teams.teams')),
            ],
            options={
                'db_table': 'custom_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('match', 'Match'), ('training', 'Training'), ('custom', 'Custom')], max_length=1024)),
                ('descritpion', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('home_team_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_away_team_set', to='teams.teams')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teams.teams')),
            ],
            options={
                'db_table': 'matches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('event_type', models.CharField(choices=[('match', 'Match'), ('training', 'Training'), ('custom', 'Custom')], max_length=1024)),
                ('descritpion', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teams.teams')),
            ],
            options={
                'db_table': 'trainings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrainingSquad',
            fields=[
                ('appearance_id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='players.players')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.trainings')),
            ],
            options={
                'db_table': 'training_squad',
                'managed': True,
            },
        ),
    ]