# Generated by Django 5.1.3 on 2025-02-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matcheventtypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matchsquad',
            options={'managed': False},
        ),
    ]
