# Generated by Django 5.1.3 on 2025-03-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(default='2025/2026', max_length=255)),
            ],
            options={
                'db_table': 'ninety_mins"."leagues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZPNs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ninety_mins"."zpns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.leagues')),
            ],
            options={
                'db_table': 'ninety_mins"."fixtures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MatchEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
                ('player', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.fixtures')),
            ],
            options={
                'db_table': 'ninety_mins"."match_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('matches', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('points', models.IntegerField()),
                ('position', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.leagues')),
            ],
            options={
                'db_table': 'ninety_mins"."table',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='leagues',
            name='zpn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.zpns'),
        ),
    ]
