create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to coachcraft;

create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to coachcraft;

create table auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table auth_permission
    owner to coachcraft;

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

create table auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table auth_group
    owner to coachcraft;

create index auth_group_name_a6ea08ec_like
    on auth_group (name varchar_pattern_ops);

create table auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table auth_group_permissions
    owner to coachcraft;

create index auth_group_permissions_group_id_b120cbf9
    on auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on auth_group_permissions (permission_id);

create table auth_user
(
    id           integer generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    email        varchar(254)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null
);

alter table auth_user
    owner to coachcraft;

create index auth_user_username_6821ab7c_like
    on auth_user (username varchar_pattern_ops);

create table auth_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  integer not null
        constraint auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    group_id integer not null
        constraint auth_user_groups_group_id_97559544_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint auth_user_groups_user_id_group_id_94350c0c_uniq
        unique (user_id, group_id)
);

alter table auth_user_groups
    owner to coachcraft;

create index auth_user_groups_user_id_6a12ed8b
    on auth_user_groups (user_id);

create index auth_user_groups_group_id_97559544
    on auth_user_groups (group_id);

create table auth_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       integer not null
        constraint auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_user_user_permissions_user_id_permission_id_14a6b632_uniq
        unique (user_id, permission_id)
);

alter table auth_user_user_permissions
    owner to coachcraft;

create index auth_user_user_permissions_user_id_a95ead1b
    on auth_user_user_permissions (user_id);

create index auth_user_user_permissions_permission_id_1fbb5f2c
    on auth_user_user_permissions (permission_id);

create table django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         integer                  not null
        constraint django_admin_log_user_id_c564eba6_fk_auth_user_id
            references auth_user
            deferrable initially deferred
);

alter table django_admin_log
    owner to coachcraft;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

create table django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table django_session
    owner to coachcraft;

create index django_session_session_key_c0390e0f_like
    on django_session (session_key varchar_pattern_ops);

create index django_session_expire_date_a5c62663
    on django_session (expire_date);

create table authtoken_token
(
    key     varchar(40)              not null
        primary key,
    created timestamp with time zone not null,
    user_id integer                  not null
        unique
        constraint authtoken_token_user_id_35299eff_fk_auth_user_id
            references auth_user
            deferrable initially deferred
);

alter table authtoken_token
    owner to coachcraft;

create index authtoken_token_key_10f0b77e_like
    on authtoken_token (key varchar_pattern_ops);

create table oauth2_provider_application
(
    id                        bigint generated by default as identity
        primary key,
    client_id                 varchar(100)             not null
        unique,
    redirect_uris             text                     not null,
    client_type               varchar(32)              not null,
    authorization_grant_type  varchar(32)              not null,
    client_secret             varchar(255)             not null,
    name                      varchar(255)             not null,
    user_id                   integer
        constraint oauth2_provider_application_user_id_79829054_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    skip_authorization        boolean                  not null,
    created                   timestamp with time zone not null,
    updated                   timestamp with time zone not null,
    algorithm                 varchar(5)               not null,
    post_logout_redirect_uris text                     not null,
    hash_client_secret        boolean                  not null,
    allowed_origins           text                     not null
);

alter table oauth2_provider_application
    owner to coachcraft;

create index oauth2_provider_application_client_id_03f0cc84_like
    on oauth2_provider_application (client_id varchar_pattern_ops);

create index oauth2_provider_application_client_secret_53133678
    on oauth2_provider_application (client_secret);

create index oauth2_provider_application_client_secret_53133678_like
    on oauth2_provider_application (client_secret varchar_pattern_ops);

create index oauth2_provider_application_user_id_79829054
    on oauth2_provider_application (user_id);

create table oauth2_provider_grant
(
    id                    bigint generated by default as identity
        primary key,
    code                  varchar(255)             not null
        unique,
    expires               timestamp with time zone not null,
    redirect_uri          text                     not null,
    scope                 text                     not null,
    application_id        bigint                   not null
        constraint oauth2_provider_gran_application_id_81923564_fk_oauth2_pr
            references oauth2_provider_application
            deferrable initially deferred,
    user_id               integer                  not null
        constraint oauth2_provider_grant_user_id_e8f62af8_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    created               timestamp with time zone not null,
    updated               timestamp with time zone not null,
    code_challenge        varchar(128)             not null,
    code_challenge_method varchar(10)              not null,
    nonce                 varchar(255)             not null,
    claims                text                     not null
);

alter table oauth2_provider_grant
    owner to coachcraft;

create index oauth2_provider_grant_code_49ab4ddf_like
    on oauth2_provider_grant (code varchar_pattern_ops);

create index oauth2_provider_grant_application_id_81923564
    on oauth2_provider_grant (application_id);

create index oauth2_provider_grant_user_id_e8f62af8
    on oauth2_provider_grant (user_id);

create table oauth2_provider_idtoken
(
    id             bigint generated by default as identity
        primary key,
    jti            uuid                     not null
        unique,
    expires        timestamp with time zone not null,
    scope          text                     not null,
    created        timestamp with time zone not null,
    updated        timestamp with time zone not null,
    application_id bigint
        constraint oauth2_provider_idto_application_id_08c5ff4f_fk_oauth2_pr
            references oauth2_provider_application
            deferrable initially deferred,
    user_id        integer
        constraint oauth2_provider_idtoken_user_id_dd512b59_fk_auth_user_id
            references auth_user
            deferrable initially deferred
);

alter table oauth2_provider_idtoken
    owner to coachcraft;

create table oauth2_provider_accesstoken
(
    id                      bigint generated by default as identity
        primary key,
    token                   text                     not null,
    expires                 timestamp with time zone not null,
    scope                   text                     not null,
    application_id          bigint
        constraint oauth2_provider_acce_application_id_b22886e1_fk_oauth2_pr
            references oauth2_provider_application
            deferrable initially deferred,
    user_id                 integer
        constraint oauth2_provider_accesstoken_user_id_6e4c9a65_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    created                 timestamp with time zone not null,
    updated                 timestamp with time zone not null,
    source_refresh_token_id bigint
        unique,
    id_token_id             bigint
        unique
        constraint oauth2_provider_acce_id_token_id_85db651b_fk_oauth2_pr
            references oauth2_provider_idtoken
            deferrable initially deferred,
    token_checksum          varchar(64)              not null
        constraint oauth2_provider_accesstoken_token_checksum_85319a26_uniq
            unique
);

alter table oauth2_provider_accesstoken
    owner to coachcraft;

create index oauth2_provider_accesstoken_application_id_b22886e1
    on oauth2_provider_accesstoken (application_id);

create index oauth2_provider_accesstoken_user_id_6e4c9a65
    on oauth2_provider_accesstoken (user_id);

create index oauth2_provider_accesstoken_token_checksum_85319a26_like
    on oauth2_provider_accesstoken (token_checksum varchar_pattern_ops);

create table oauth2_provider_refreshtoken
(
    id              bigint generated by default as identity
        primary key,
    token           varchar(255)             not null,
    access_token_id bigint
        unique
        constraint oauth2_provider_refr_access_token_id_775e84e8_fk_oauth2_pr
            references oauth2_provider_accesstoken
            deferrable initially deferred,
    application_id  bigint                   not null
        constraint oauth2_provider_refr_application_id_2d1c311b_fk_oauth2_pr
            references oauth2_provider_application
            deferrable initially deferred,
    user_id         integer                  not null
        constraint oauth2_provider_refreshtoken_user_id_da837fce_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    created         timestamp with time zone not null,
    updated         timestamp with time zone not null,
    revoked         timestamp with time zone,
    token_family    uuid,
    constraint oauth2_provider_refreshtoken_token_revoked_af8a5134_uniq
        unique (token, revoked)
);

alter table oauth2_provider_refreshtoken
    owner to coachcraft;

alter table oauth2_provider_accesstoken
    add constraint oauth2_provider_acce_source_refresh_token_e66fbc72_fk_oauth2_pr
        foreign key (source_refresh_token_id) references oauth2_provider_refreshtoken
            deferrable initially deferred;

create index oauth2_provider_refreshtoken_application_id_2d1c311b
    on oauth2_provider_refreshtoken (application_id);

create index oauth2_provider_refreshtoken_user_id_da837fce
    on oauth2_provider_refreshtoken (user_id);

create index oauth2_provider_idtoken_application_id_08c5ff4f
    on oauth2_provider_idtoken (application_id);

create index oauth2_provider_idtoken_user_id_dd512b59
    on oauth2_provider_idtoken (user_id);

create table roles
(
    id        integer generated by default as identity
        primary key,
    role_name varchar(64)
);

alter table roles
    owner to coachcraft;

create table user_roles
(
    id      integer generated by default as identity
        primary key,
    user_id integer not null
        references auth_user,
    role_id integer not null
        references roles
);

alter table user_roles
    owner to coachcraft;

create table teams
(
    id        integer generated by default as identity
        primary key,
    team_name varchar(64),
    logo      varchar(1024)
);

alter table teams
    owner to coachcraft;

create table user_teams
(
    id      integer generated by default as identity
        primary key,
    user_id integer not null
        references auth_user,
    team_id integer not null
        references teams
);

alter table user_teams
    owner to coachcraft;

create table players
(
    id         integer generated by default as identity
        primary key,
    first_name varchar(64),
    last_name  varchar(64),
    country    varchar(5),
    birthdate  date
);

alter table players
    owner to coachcraft;

create table players_affilations
(
    id         integer generated by default as identity
        primary key,
    player_id  integer not null
        references players,
    team_id    integer not null
        references teams,
    start_date date    not null,
    end_date   date
);

alter table players_affilations
    owner to coachcraft;

create table ratings
(
    id              integer generated by default as identity
        primary key,
    training_id     integer,
    match_id        integer,
    player_id       integer not null
        references players,
    rating          integer,
    ratings_user_id integer
        constraint ratings_auth_user_id_fk
            references auth_user
);

alter table ratings
    owner to coachcraft;

create table match_events
(
    id     bigint generated by default as identity
        primary key,
    minute integer not null,
    half   integer
);

alter table match_events
    owner to coachcraft;

create table match_event_types
(
    id   integer generated by default as identity
        primary key,
    name varchar(1024) not null,
    icon varchar(1024),
    type varchar(1024) not null
);

alter table match_event_types
    owner to coachcraft;

create table match_squad
(
    id           bigint generated by default as identity
        primary key,
    is_home_team boolean,
    numer        integer
);

alter table match_squad
    owner to coachcraft;

create table custom_events
(
    id          bigint generated by default as identity
        primary key,
    event_type  varchar(1024)            not null,
    descritpion text,
    timestamp   timestamp with time zone not null,
    location    varchar(1024),
    duration    integer,
    team_id     bigint                   not null
        constraint custom_events_team_id_09d47358_fk_teams_id
            references teams
            deferrable initially deferred
);

alter table custom_events
    owner to coachcraft;

create index custom_events_team_id_09d47358
    on custom_events (team_id);

create table matches
(
    id             bigint generated by default as identity
        primary key,
    event_type     varchar(1024)            not null,
    descritpion    text,
    timestamp      timestamp with time zone not null,
    location       varchar(1024),
    duration       integer,
    home_team_name varchar(1024),
    away_team_name varchar(1024),
    away_team_id   bigint
        constraint matches_away_team_id_e9ac1ee8_fk_teams_id
            references teams
            deferrable initially deferred,
    home_team_id   bigint
        constraint matches_home_team_id_d79411d2_fk_teams_id
            references teams
            deferrable initially deferred
);

alter table matches
    owner to coachcraft;

create index matches_away_team_id_e9ac1ee8
    on matches (away_team_id);

create index matches_home_team_id_d79411d2
    on matches (home_team_id);

create table trainings
(
    event_type  varchar(1024)            not null,
    descritpion text,
    timestamp   timestamp with time zone not null,
    location    varchar(1024),
    duration    integer,
    id          integer generated by default as identity
        primary key,
    team_id     bigint                   not null
        constraint trainings_team_id_e4f13ca0_fk_teams_id
            references teams
            deferrable initially deferred
);

alter table trainings
    owner to coachcraft;

create index trainings_team_id_e4f13ca0
    on trainings (team_id);

create table training_squad
(
    appearance_id integer generated by default as identity
        primary key,
    player_id     bigint  not null
        constraint training_squad_player_id_23f14cb8_fk_players_id
            references players
            deferrable initially deferred,
    training_id   integer not null
        constraint training_squad_training_id_2e38c36a_fk_trainings_id
            references trainings
            deferrable initially deferred
);

alter table training_squad
    owner to coachcraft;

create index training_squad_player_id_23f14cb8
    on training_squad (player_id);

create index training_squad_training_id_2e38c36a
    on training_squad (training_id);

create table user_data
(
    user_id    integer not null
        primary key
        constraint user_data_user_id_11b692a9_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    phone      varchar(1024),
    birth_date date,
    avatar     varchar(1024),
    bio        text
);

alter table user_data
    owner to coachcraft;

create view actual_players_affiliations(id, player_id, team_id) as
SELECT row_number() OVER () AS id,
       p.id                 AS player_id,
       t.id                 AS team_id
FROM players p,
     teams t,
     players_affilations pa
WHERE p.id = pa.player_id
  AND t.id = pa.team_id
  AND pa.end_date IS NULL;

alter table actual_players_affiliations
    owner to coachcraft;

create function create_user_data() returns trigger
    language plpgsql
as
$$
BEGIN
    INSERT INTO user_data(user_id, phone, birth_date, avatar, bio)
    VALUES (
        NEW.id,
        NULL,
        NULL,
        'default_user.png',
        'Hi!'
    );
    RETURN NEW;
END;
$$;

alter function create_user_data() owner to coachcraft;

create trigger create_user_data_ai
    after insert
    on auth_user
    for each row
execute procedure create_user_data();

